### ISSUE TITLE
README.md fajlovi

### ISSUE THREAD

**Issue by F-zivanovic** [webfax-org/CSS-projects#1]
Za **sve navedene repozitorijume** dodati README.md fajl. 
README.md fajlovi treba sa sadrze linkove (live preview) ka svakom pojedinacnom projektu u repozitorijumu.

**Koristiti GitHub pages.**

**Comment by D-vokic** [comment]
Урадио сам тако како сам мислио да треба. Надам се да је добро.

**Comment by F-zivanovic** [comment]
Sve je u redu.
